### ISSUE TITLE
UnicodeDecodeError

### ISSUE THREAD

**Issue by nmweizi** [shenril/Sitadel#17]
[i] Checking common backup files..
Traceback (most recent call last):
  File "sitadel.py", line 93, in <module>
    Sitadel().main()
  File "sitadel.py", line 88, in main
    self.ma.attacks(args.attack, self.url, discovered_urls)
  File "/root/tools/Sitadel/lib/utils/manager.py", line 29, in attacks
    Attacks(url, crawled_urls).run(plugins)
  File "/root/tools/Sitadel/lib/modules/attacks/__init__.py", line 45, in run
    raise (e)
  File "/root/tools/Sitadel/lib/modules/attacks/__init__.py", line 39, in run
    attacks = ([(p(), p().process(self.start_url, self.crawled_urls)) for p in AttackPlugin.plugins])
  File "/root/tools/Sitadel/lib/modules/attacks/__init__.py", line 39, in <listcomp>
    attacks = ([(p(), p().process(self.start_url, self.crawled_urls)) for p in AttackPlugin.plugins])
  File "/root/tools/Sitadel/lib/modules/attacks/bruteforce/bfile.py", line 17, in process
    dbfiles1 = [x for x in db1.readlines()]
  File "/usr/lib64/python3.6/encodings/ascii.py", line 26, in decode
    return codecs.ascii_decode(input, self.errors)[0]
UnicodeDecodeError: 'ascii' codec can't decode byte 0xd0 in position 6559: ordinal not in range(128)

**Comment by shenril** [comment]
Hello , 
Could you tell me your OS and python version?

**Comment by shenril** [comment]
@nmweizi i pushed a fix that should solve this problem
Is your PC in a special language ? Chinese?

**Comment by nmweizi** [comment]
centos7，python3.7

**Comment by nmweizi** [comment]
html is in a special language 
Chinese

**Comment by shenril** [comment]
@nmweizi Could you tell me if my update solved your problem?

**Comment by nmweizi** [comment]
@shenril Need to wait, there is no environment. Thank you

**Comment by nmweizi** [comment]
is fine.
thx
