### ISSUE TITLE
AttributeError: module 'collections' has no attribute 'Hashable'

### ISSUE THREAD

**Issue by sedorf** [shenril/Sitadel#47]
└─$ python sitadel.py https://site.com
   _   _   _        ______ _                 _       _  
  | |_| |_| |      / _____|_)  _            | |     | | 
  |         |     ( (____  _ _| |_ _____  __| |_____| | 
  |    _    |      \____ \| (_   _|____ |/ _  | ___ | | 
  |   |_|   |      _____) ) | | |_/ ___ ( (_| | ____| | 
  |         |     (______/|_|  \__)_____|\____|_____)\_) 1.0.1
                                                                                                                                                       
~/# Sitadel - Web Application Security Scanner #\~
~/# Shenril (@shenril) #\~
~/# https://github.com/shenril/Sitadel #\~

Traceback (most recent call last):
  File "/home/pc/Desktop/Sitadel/sitadel.py", line 174, in <module>
    Sitadel().main()
  File "/home/pc/Desktop/Sitadel/sitadel.py", line 99, in main
    settings.from_yaml(args.config)
  File "/home/pc/Desktop/Sitadel/lib/config/settings.py", line 48, in from_yaml
    config = yaml.load(yamlfile, Loader=yaml.SafeLoader)
  File "/usr/local/lib/python3.10/dist-packages/yaml/__init__.py", line 72, in load
    return loader.get_single_data()
  File "/usr/local/lib/python3.10/dist-packages/yaml/constructor.py", line 37, in get_single_data
    return self.construct_document(node)
  File "/usr/local/lib/python3.10/dist-packages/yaml/constructor.py", line 46, in construct_document
    for dummy in generator:
  File "/usr/local/lib/python3.10/dist-packages/yaml/constructor.py", line 398, in construct_yaml_map
    value = self.construct_mapping(node)
  File "/usr/local/lib/python3.10/dist-packages/yaml/constructor.py", line 204, in construct_mapping
    return super().construct_mapping(node, deep=deep)
  File "/usr/local/lib/python3.10/dist-packages/yaml/constructor.py", line 126, in construct_mapping
    if not isinstance(key, collections.Hashable):
AttributeError: module 'collections' has no attribute 'Hashable'

**Comment by shenril** [comment]
Hello to you too 

Could you tell me your environment/ python version ?

**Comment by sedorf** [comment]
hello @shenril , 

i use kali linux , Python 3.10.7

**Comment by shenril** [comment]
**Status: still latent.** Sitadel's own code is fine; the crash comes from an outdated PyYAML, and nothing in `setup.py` prevents that old version from being installed.

## Description
Startup crashes in `settings.from_yaml()` while parsing the config:

```
File ".../yaml/constructor.py", line 126, in construct_mapping
    if not isinstance(key, collections.Hashable):
AttributeError: module 'collections' has no attribute 'Hashable'
```

## Root cause
This is **not** a bug in Sitadel — the traceback ends inside **PyYAML**, not Sitadel. `collections.Hashable` was moved to `collections.abc.Hashable` in Python 3.3 and the old top-level alias was **removed in Python 3.10**. PyYAML versions **< 5.3** still referenced `collections.Hashable` in `constructor.py`, so any old PyYAML on Python ≥ 3.10 raises this `AttributeError`. PyYAML 5.3 (2020) fixed it.

Sitadel already calls `yaml.load(..., Loader=yaml.SafeLoader)` correctly. The problem survives only because `setup.py` declares a bare, unpinned dependency:

```python
install_requires=[
    "requests",
    "urllib3",
    "pyyaml",     # <-- no minimum version
    "colorama",
    "scrapy",
]
```

so an environment with an old cached PyYAML is never upgraded.

## Possible solution
Pin a minimum PyYAML version in `setup.py`:

```python
"pyyaml>=5.4",   # (>=6.0 recommended)
```

Users hitting this today can fix it immediately with:

```bash
pip install -U pyyaml
```

Verified: current PyYAML 6.x parses `config/config.yml` with `SafeLoader` on modern Python without error, so a version floor closes the issue for good.
