### ISSUE TITLE
system-wide installation: No such file or directory: 'lib/data/admin.txt'

### ISSUE THREAD

**Issue by blshkv** [shenril/Sitadel#48]
## Environment

- OS: Pentoo (I'm a developer)
- Python version 3.11, 3.12
- Sitadel version: latest git

First of all, config.yml was not installed by default, I had to extract it to a local folder.
It would be good to install it, copy to a user's folder (~/.siteadel/config.yml)

And when, after running it:
## Current Behavior

```
---------  Scan Started: 27/02/2024 09:28:01 ---------
[i] Launching fingerprints modules...
[i] For better waf detection we recommend you to run with --no-redirect
[+] X-Frame-Options header is not present.
[+] X-XSS-Protection header is not present.
[+] Lang detected: Java
[+] Server detected: nginx
[i] Start crawling the target website
[i] Launching attacks modules...
[i] Checking admin interfaces...
sitadelLog - ERROR - [Errno 2] No such file or directory: 'lib/data/admin.txt'
---------  Scan Finished: 27/02/2024 09:28:08 ---------
Traceback (most recent call last):
  File "/usr/lib/python-exec/python3.12/sitadel.py", line 174, in <module>
    Sitadel().main()
  File "/usr/lib/python-exec/python3.12/sitadel.py", line 165, in main
    self.ma.attacks(args.attack, self.url, discovered_urls)
  File "/usr/lib/python3.12/site-packages/lib/utils/manager.py", line 25, in attacks
    Attacks(url, crawled_urls).run(plugins)
  File "/usr/lib/python3.12/site-packages/lib/modules/attacks/__init__.py", line 56, in run
    raise e
  File "/usr/lib/python3.12/site-packages/lib/modules/attacks/__init__.py", line 43, in run
    (p(), p().process(self.start_url, self.crawled_urls))
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/site-packages/lib/modules/attacks/bruteforce/admin.py", line 28, in process
    with self.datastore.open("admin.txt", "r") as db:
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/site-packages/lib/utils/datastore.py", line 13, in open
    return open(os.path.join(self.rootpath, filename), mode,encoding="utf-8")
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
FileNotFoundError: [Errno 2] No such file or directory: 'lib/data/admin.txt'

```
I checked and confirmed, that ```/usr/lib/python3.12/site-packages/lib/data/admin.txt``` file does exist.

Tell us what happens instead of the expected behavior
The "lib" directory should be discovered

## To Reproduce

1) run ```python setup.py install```
It should be possible to use ```--user``` and ```--prefix``` to install to a local folder, and run it from home folder

2) run $ sitadel.py --config <file> https://<url>

**Comment by blshkv** [comment]
feel free to see https://github.com/derv82/wifite2/issues/102  how to install data files  (```package_data```)

**Comment by shenril** [comment]
**Status: still reproducible on `master`** for any out-of-tree / system-wide install.

## Description
After installing Sitadel (so the code lives in `site-packages/`) and running it from a directory other than the source checkout, the attack phase fails to open the packaged wordlists:

```
sitadelLog - ERROR - [Errno 2] No such file or directory: 'lib/data/admin.txt'
```

even though `.../site-packages/lib/data/admin.txt` does exist.

## Root cause
The datastore root is a **relative** path and is resolved against the **current working directory**, not the installed package.

`config/config.yml`:
```yaml
datastore: lib/data
```

`lib/utils/datastore.py`:
```python
def open(self, filename, mode):
    return open(os.path.join(self.rootpath, filename), mode, encoding="utf-8")
```

With `rootpath = "lib/data"`, `os.path.join("lib/data", "admin.txt")` → `"lib/data/admin.txt"`, which Python resolves relative to `os.getcwd()`. It only works when you happen to run from the repo root. The default `--config config/config.yml` in `sitadel.py` has the same CWD-relative problem. The data files *are* shipped inside the package (`MANIFEST.in` + `include_package_data`), but the code never points at that location.

## Possible solution
Anchor the datastore path to the package location whenever it is not absolute. For example, in `lib/utils/datastore.py`:

```python
import os
import lib  # the package root

PACKAGE_ROOT = os.path.dirname(os.path.dirname(os.path.abspath(lib.__file__)))

class Datastore:
    def __init__(self, rootpath):
        self.rootpath = rootpath if os.path.isabs(rootpath) \
            else os.path.join(PACKAGE_ROOT, rootpath)
```

(or resolve via `importlib.resources.files("lib") / "data"`).

For the config, do the same: fall back to a packaged default `config.yml` when the CWD-relative path is missing, and/or copy it to `~/.sitadel/config.yml` on first run (as suggested in the report). That makes `sitadel <url>` work from any directory after a normal install.

**Comment by blshkv** [comment]
There is a regression:
```
 * 
 * QA Notice: The following unexpected files/directories were found
 * top-level in the site-packages directory:
 * 
 *   /usr/lib/python3.14/site-packages/lib
 * 
 * This is most likely a bug in the build system.  More information
 * can be found in the Python Guide:
 * https://projects.gentoo.org/python/guide/qawarn.html#stray-top-level-files-in-site-packages
 ```

Please reopen the issue, I'm unable to.
